#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:3001/eureka/

spring:
  application:
    name: smc-stock-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:33061/smcdb
    username: admin
    password: passw0rd

server:
  port: 3004
  servlet:
    context-path: /api
    
debug: false